### PR TITLE
Add Readme and bootstrap script

### PR DESCRIPTION
**Pull request by pezholio**
I've added a Readme with basic information on how to use the service, as well as information on getting it running in development, and a bootstrap script (`rake bootstrap`). 

I've uploaded the DB dump of reference tables to the Open Addresses S3 account, so the bootstrap script downloads this, imports the relevant collections, and runs the elasticsearch indexes, then cleans up after itself. 

If someone could test this out before merging, that'd be great!

### CODE REVIEW

**Comment by pikesley** [comment]
This needs a local ElasticSearch I presume?

**Comment by pezholio** [comment]
Das ist richtig :+1:

**Comment by pikesley** [comment]
OH GOD JAVA

**Comment by pezholio** [comment]
:runner: :japanese_ogre:

**Comment by pikesley** [comment]
```
➔  bundle exec rake bootstrap
Downloading the database dump...
Extracting the files...
Importing the data...
sh: line 1: 17068 Abort trap: 6           mongorestore --db distiller ./dump/distiller 2>&1
Running the indexes...
Cleaning up...
Done!
```

Is that right?

**Comment by pezholio** [comment]
Can you try `rspec spec/big_old_list_spec.rb`? If you get 8 fails, we're good.

**Comment by pikesley** [comment]
25 examples, 25 failures

**Comment by pezholio** [comment]
Ah fucksticks. Something wrong with the mongoimport then I think. Can you try the steps in the Rakefile manually? (without supressing the output)

**Comment by pikesley** [comment]
I will try this again

**Comment by pikesley** [comment]
```
➔ bundle exec rake bootstrap
Downloading the database dump...
Extracting the files...
Importing the data...
Running the indexes...
Cleaning up...
Done!
```

FTW

**Comment by pikesley** [comment]
```
➔ rspec spec/big_old_list_spec.rb
.F..F.F......F.F.F...F.F.

Finished in 2.3 seconds (files took 2.03 seconds to load)
25 examples, 8 failures
```

Win

**Pull request merged**
