### PR TITLE
Use Levenshtein distance

### PR DESCRIPTION
**Pull request by pezholio**
Just occured to me that this might be useful

### CODE REVIEW

**Comment by Floppy** [comment]
That's a good idea, but one possible problem is that Levenshtein is really bad for strings of different length. I used `similar_text` for some analysis I did recently, might be better?

**Comment by pezholio** [comment]
I think all I'm after here is finding the most similar string, so, for example if there's a 'High Street' and an 'Upper High Street' in close proximity and the address is 123 Upper High Street, I want 'Upper High Street' to be chosen, which will have a closer Levenshtein distance. I'll have a look at `similar_text` though

**Comment by Floppy** [comment]
Yes, it's probably fine in that case. Just thought I'd mention it :)

**Comment by pezholio** [comment]
Actually, though, that might be a good replacement for the logic here https://github.com/OpenAddressesUK/sorting_office/blob/master/lib/sorting_office/models/street.rb#L14, so rather than using a regex, we use `similar_text`, that may also get around shortened suffixes (like st. for street etc)

**Comment by pezholio** [comment]
Actually, that might give a few false positives, so this one can be merged

**Comment by Floppy** [comment]
OK!

**Pull request merged**
